Repository dotnet/yarp, pull requests merged in 2020-09, with the labels that each got.

#382 Move to the preview.8 SDK
  azure-pipelines.yml
  global.json
Labels: Blocked

#414 Disable broken validation steps
  azure-pipelines.yml
Labels: Auto-Merge

#411 Removed '*Options' suffixes from 'Abstractions.Cluster' properties
  docs/docfx/articles/proxyhttpclientconfig.md
  samples/ReverseProxy.Code.Sample/CustomConfigFilter.cs
  samples/ReverseProxy.Config.Sample/CustomConfigFilter.cs
  src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/Cluster.cs
  src/ReverseProxy/Configuration/ConfigurationConfigProvider.cs
  src/ReverseProxy/Service/Management/ProxyConfigManager.cs
  test/ReverseProxy.Tests/Abstractions/ClusterDiscovery/Contract/ClusterTests.cs
  test/ReverseProxy.Tests/Configuration/ConfigurationConfigProviderTests.cs
  test/ReverseProxy.Tests/Service/Management/ProxyConfigManagerTests.cs
Labels: Breaking-Change

#366 Implement Equals for ProxyRoute & Cluster
  src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/CircuitBreakerOptions.cs
  src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/Cluster.cs
  src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/ClusterPartitioningOptions.cs
  src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/HealthCheckOptions.cs
  src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/LoadBalancingOptions.cs
  src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/ProxyHttpClientOptions.cs
  src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/QuotaOptions.cs
  src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/SessionAffinityOptions.cs
  src/ReverseProxy/Abstractions/DestinationDiscovery/Contract/Destination.cs
  src/ReverseProxy/Abstractions/RouteDiscovery/Contract/ProxyMatch.cs
  src/ReverseProxy/Abstractions/RouteDiscovery/Contract/ProxyRoute.cs
  src/ReverseProxy/Service/Config/RuntimeRouteBuilder.cs
  src/ReverseProxy/Service/Management/ProxyConfigManager.cs
  src/ReverseProxy/Service/RuntimeModel/ClusterConfig.cs
  src/ReverseProxy/Service/RuntimeModel/RouteConfig.cs
  src/ReverseProxy/Utilities/CaseInsensitiveEqualHelper.cs
  test/ReverseProxy.Tests/Abstractions/ClusterDiscovery/Contract/CircuitBreakerOptionsTests.cs
  test/ReverseProxy.Tests/Abstractions/ClusterDiscovery/Contract/ClusterPartitioningOptionsTests.cs
  test/ReverseProxy.Tests/Abstractions/ClusterDiscovery/Contract/HealthCheckOptionsTests.cs
  test/ReverseProxy.Tests/Abstractions/ClusterDiscovery/Contract/LoadBalancingOptionsTests.cs
  test/ReverseProxy.Tests/Abstractions/ClusterDiscovery/Contract/ProxyHttpClientOptionsTests.cs
  test/ReverseProxy.Tests/Abstractions/ClusterDiscovery/Contract/QuotaOptionsTests.cs
  test/ReverseProxy.Tests/Abstractions/ClusterDiscovery/Contract/SessionAffinityOptionsTests.cs
  test/ReverseProxy.Tests/Middleware/AffinityMiddlewareTestBase.cs
  test/ReverseProxy.Tests/Middleware/DestinationInitializerMiddlewareTests.cs
  test/ReverseProxy.Tests/Middleware/LoadBalancerMiddlewareTests.cs
  test/ReverseProxy.Tests/Middleware/ProxyInvokerMiddlewareTests.cs
  test/ReverseProxy.Tests/Service/Config/RuntimeRouteBuilderTests.cs
  test/ReverseProxy.Tests/Service/RuntimeModel/ClusterInfoTests.cs
  test/ReverseProxy.Tests/Utilities/CaseInsensitiveEqualHelperTests.cs
Labels: Auto-Merge
