Repository dotnet/yarp, pull requests merged in 2020-07, with the labels that each got.

#280 Add instructions for using daily builds
  README.md
  docs/DailyBuilds.md
Labels: Auto-Merge

#287 Remove Anonymous from AuthorizationPolicy summary
  src/ReverseProxy/Abstractions/RouteDiscovery/Contract/ProxyRoute.cs
  src/ReverseProxy/Service/ConfigModel/ParsedRoute.cs
Labels: Auto-Merge

#297 Support Multiple Hosts for a Route
  docs/docfx/articles/authn-authz.md
  docs/docfx/articles/getting_started.md
  docs/docfx/articles/transforms.md
  samples/ReverseProxy.Sample/appsettings.json
  src/ReverseProxy/Abstractions/RouteDiscovery/Contract/ProxyMatch.cs
  src/ReverseProxy/Service/Config/DynamicConfigBuilder.cs
  src/ReverseProxy/Service/Config/RuleParsing/RouteValidator.cs
  src/ReverseProxy/Service/ConfigModel/ParsedRoute.cs
  src/ReverseProxy/Service/DynamicEndpoints/RuntimeRouteBuilder.cs
  test/ReverseProxy.Tests/Abstractions/RouteDiscovery/Contract/ProxyRouteTests.cs
  test/ReverseProxy.Tests/Service/Config/DynamicConfigBuilderTests.cs
  test/ReverseProxy.Tests/Service/Config/RuleParsing/RouteValidatorTests.cs
  test/ReverseProxy.Tests/Service/DynamicEndpoints/RuntimeRouteBuilderTests.cs
Labels: Breaking-Change

#314 Remove trivial uses of operation logging
  src/ReverseProxy/Middleware/AffinitizeRequestMiddleware.cs
  src/ReverseProxy/Middleware/AffinitizedDestinationLookupMiddleware.cs
  src/ReverseProxy/Middleware/LoadBalancingMiddleware.cs
  test/ReverseProxy.Tests/Middleware/AffinitizeRequestMiddlewareTests.cs
  test/ReverseProxy.Tests/Middleware/AffinitizedDestinationLookupMiddlewareTests.cs
Labels: Auto-Merge

#343 Fix articles TOC
  docs/docfx/articles/toc.yml
Labels: Type: Documentation
