Repository dotnet/yarp, pull requests merged in 2020-12, with the labels that each got.

#577 Service Fabric integration docs
  docs/docfx/articles/direct-proxying.md
  docs/docfx/articles/service-fabric-int.md
  docs/docfx/articles/toc.yml
Labels: Type: Documentation

#597 Change IAffinityFailurePolicy to public
  src/ReverseProxy/Service/SessionAffinity/IAffinityFailurePolicy.cs
Labels: Auto-Merge

#600 Make load-balancing extensible
  docs/docfx/articles/load-balancing.md
  docs/docfx/articles/proxyhttpclientconfig.md
  docs/docfx/articles/service-fabric-int.md
  docs/docfx/articles/session-affinity.md
  samples/ReverseProxy.Config.Sample/appsettings.json
  src/ReverseProxy.ServiceFabric/ServiceDiscovery/Util/LabelsParser.cs
  src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/Cluster.cs
  src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/LoadBalancingMode.cs
  src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/LoadBalancingOptions.cs
  src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/LoadBalancingPolicies.cs
  src/ReverseProxy/Configuration/ConfigurationConfigProvider.cs
  src/ReverseProxy/Configuration/DependencyInjection/BuilderExtensions/IReverseProxyBuilderExtensions.cs
  src/ReverseProxy/Configuration/DependencyInjection/ReverseProxyServiceCollectionExtensions.cs
  src/ReverseProxy/Middleware/LoadBalancingMiddleware.cs
  src/ReverseProxy/Service/Config/ConfigValidator.cs
  src/ReverseProxy/Service/LoadBalancing/FirstLoadBalancingPolicy.cs
  src/ReverseProxy/Service/LoadBalancing/ILoadBalancingPolicy.cs
  src/ReverseProxy/Service/LoadBalancing/LeastRequestsLoadBalancingPolicy.cs
  src/ReverseProxy/Service/LoadBalancing/PowerOfTwoChoicesLoadBalancingPolicy.cs
  src/ReverseProxy/Service/LoadBalancing/RandomLoadBalancingPolicy.cs
  src/ReverseProxy/Service/LoadBalancing/RoundRobinLoadBalancingPolicy.cs
  src/ReverseProxy/Service/Management/ProxyConfigManager.cs
  src/ReverseProxy/Service/Proxy/LoadBalancer.cs
  src/ReverseProxy/Service/RuntimeModel/ClusterConfig.cs
  src/ReverseProxy/Service/RuntimeModel/ClusterLoadBalancingOptions.cs
  src/ReverseProxy/Service/SessionAffinity/BaseSessionAffinityProvider.cs
  src/ReverseProxy/Utilities/ServiceLookupHelper.cs
  test/ReverseProxy.ServiceFabric.Tests/ServiceDiscovery/Util/LabelsParserTests.cs
  test/ReverseProxy.Tests/Abstractions/ClusterDiscovery/Contract/ClusterTests.cs
  test/ReverseProxy.Tests/Abstractions/ClusterDiscovery/Contract/LoadBalancingOptionsTests.cs
  test/ReverseProxy.Tests/Configuration/ConfigurationConfigProviderTests.cs
  test/ReverseProxy.Tests/Middleware/DestinationInitializerMiddlewareTests.cs
  test/ReverseProxy.Tests/Middleware/LoadBalancerMiddlewareTests.cs
  test/ReverseProxy.Tests/Service/Config/ConfigValidatorTests.cs
  test/ReverseProxy.Tests/Service/Proxy/LoadBalancerTests.cs
  test/ReverseProxy.Tests/Service/Proxy/LoadBalancingPoliciesTests.cs
  test/ReverseProxy.Tests/Service/RuntimeModel/ClusterInfoTests.cs
Labels: Breaking-Change

#632 Support Anonymous in ProxyRoute.AuthorizationPolicy
  docs/docfx/articles/authn-authz.md
  src/ReverseProxy/Abstractions/RouteDiscovery/Contract/AuthorizationConstants.cs
  src/ReverseProxy/Abstractions/RouteDiscovery/Contract/ProxyRoute.cs
  src/ReverseProxy/Service/Config/ConfigValidator.cs
  src/ReverseProxy/Service/DynamicEndpoint/ProxyEndpointFactory.cs
  test/ReverseProxy.Tests/Service/DynamicEndpoint/ProxyEndpointFactorTests.cs
Labels: Auto-Merge
