Repository dotnet/yarp, pull requests merged in 2021-04, with the labels that each got.

#897 Rename X-Fowarded-PathBase to X-Forwarded-Prefix
  docs/docfx/articles/transforms.md
  src/ReverseProxy/Abstractions/Config/ForwardedTransformExtensions.cs
  src/ReverseProxy/Service/Config/ForwardedTransformFactory.cs
  src/ReverseProxy/Service/RuntimeModel/Transforms/RequestHeaderXForwardedPrefixTransform.cs
  test/ReverseProxy.Tests/Abstractions/Config/ForwardedTransformExtensionsTests.cs
  test/ReverseProxy.Tests/Service/Config/TransformBuilderTests.cs
  test/ReverseProxy.Tests/Service/RuntimeModel/Transforms/RequestHeaderXForwardedPrefixTransformTests.cs
  testassets/ReverseProxy.Config/appsettings.json
Labels: Breaking-Change

#900 Change routes from array to object
  docs/docfx/articles/authn-authz.md
  docs/docfx/articles/configfiles.md
  docs/docfx/articles/configproviders.md
  docs/docfx/articles/cors.md
  docs/docfx/articles/getting_started.md
  docs/docfx/articles/header-routing.md
  docs/docfx/articles/transforms.md
  samples/BasicYarpSample/BasicYarpSample.csproj
  samples/BasicYarpSample/appsettings.json
  samples/ReverseProxy.Auth.Sample/ReverseProxy.Auth.Sample.csproj
  samples/ReverseProxy.Auth.Sample/appsettings.json
  samples/ReverseProxy.Code.Sample/ReverseProxy.Code.Sample.csproj
  samples/ReverseProxy.Config.Sample/ReverseProxy.Config.Sample.csproj
  samples/ReverseProxy.Config.Sample/appsettings.json
  samples/ReverseProxy.ConfigFilter.Sample/ReverseProxy.ConfigFilter.Sample.csproj
  samples/ReverseProxy.ConfigFilter.Sample/appsettings.json
  samples/ReverseProxy.Direct.Sample/ReverseProxy.Direct.Sample.csproj
  samples/ReverseProxy.Direct.Sample/Startup.cs
  samples/ReverseProxy.Metrics.Sample/ReverseProxy.Metrics.Sample.csproj
  samples/ReverseProxy.Metrics.Sample/appsettings.json
  samples/ReverseProxy.ServiceFabric.Sample/ReverseProxy.ServiceFabric.Sample.csproj
  samples/ReverseProxy.Transforms.Sample/ReverseProxy.Transforms.Sample.csproj
  samples/ReverseProxy.Transforms.Sample/appsettings.json
  src/ReverseProxy/Configuration/ConfigurationConfigProvider.cs
  test/ReverseProxy.Tests/Configuration/ConfigurationConfigProviderTests.cs
  testassets/BenchmarkApp/Startup.cs
  testassets/ReverseProxy.Config/appsettings.json
Labels: Breaking-Change

#886 Remove ItemManager classes, make ClusterInfo ctor public
  src/ReverseProxy/Abstractions/ClusterDiscovery/Contract/Cluster.cs
  src/ReverseProxy/Configuration/DependencyInjection/BuilderExtensions/IReverseProxyBuilderExtensions.cs
  src/ReverseProxy/Service/Management/ClusterManager.cs
  src/ReverseProxy/Service/Management/DestinationManager.cs
  src/ReverseProxy/Service/Management/DestinationManagerFactory.cs
  src/ReverseProxy/Service/Management/IClusterManager.cs
  src/ReverseProxy/Service/Management/IDestinationManager.cs
  src/ReverseProxy/Service/Management/IDestinationManagerFactory.cs
  src/ReverseProxy/Service/Management/IItemManager.cs
  src/ReverseProxy/Service/Management/IRouteManager.cs
  src/ReverseProxy/Service/Management/ItemManagerBase.cs
  src/ReverseProxy/Service/Management/ProxyConfigManager.cs
  src/ReverseProxy/Service/Management/RouteManager.cs
  src/ReverseProxy/Service/RuntimeModel/ClusterConfig.cs
  src/ReverseProxy/Service/RuntimeModel/ClusterInfo.cs
  test/ReverseProxy.Tests/DynamicEndpoint/ReverseProxyConventionBuilderTests.cs
  test/ReverseProxy.Tests/Middleware/AffinitizedDestinationLookupMiddlewareTests.cs
  test/ReverseProxy.Tests/Middleware/AffinityMiddlewareTestBase.cs
  test/ReverseProxy.Tests/Middleware/DestinationInitializerMiddlewareTests.cs
  test/ReverseProxy.Tests/Middleware/LoadBalancerMiddlewareTests.cs
  test/ReverseProxy.Tests/Middleware/PassiveHealthCheckMiddlewareTests.cs
  test/ReverseProxy.Tests/Middleware/ProxyInvokerMiddlewareTests.cs
  test/ReverseProxy.Tests/Service/DynamicEndpoint/ProxyEndpointFactoryTests.cs
  test/ReverseProxy.Tests/Service/HealthChecks/ActiveHealthCheckMonitorTests.cs
  test/ReverseProxy.Tests/Service/HealthChecks/ConsecutiveFailuresHealthPolicyTests.cs
  test/ReverseProxy.Tests/Service/HealthChecks/DestinationHealthUpdaterTests.cs
  test/ReverseProxy.Tests/Service/HealthChecks/TransportFailureRateHealthPolicyTests.cs
  test/ReverseProxy.Tests/Service/Management/ClusterManagerTests.cs
  test/ReverseProxy.Tests/Service/Management/DestinationManagerFactoryTests.cs
  test/ReverseProxy.Tests/Service/Management/DestinationManagerTests.cs
  test/ReverseProxy.Tests/Service/Management/ItemManagerBaseTests.cs
  test/ReverseProxy.Tests/Service/Management/ProxyConfigManagerTests.cs
  test/ReverseProxy.Tests/Service/Management/RouteManagerTests.cs
  test/ReverseProxy.Tests/Service/Proxy/LoadBalancingPoliciesTests.cs
  test/ReverseProxy.Tests/Service/RuntimeModel/ClusterInfoTests.cs
  test/ReverseProxy.Tests/Service/SessionAffinity/AffinitizeTransformTests.cs
Labels: Auto-Merge

#925 React to API breaks in samples
  samples/ReverseProxy.Code.Sample/Startup.cs
Labels: Auto-Merge

#929 API renames: ProxyMatch, AddProxyConfigFilter, ConfigureClient
  src/ReverseProxy.Kubernetes.Controller/Converters/YarpParser.cs
  src/ReverseProxy.ServiceFabric/ServiceDiscovery/Util/LabelsParser.cs
  src/ReverseProxy/Abstractions/RouteDiscovery/Contract/ProxyRoute.cs
  src/ReverseProxy/Abstractions/RouteDiscovery/Contract/RouteMatch.cs
  src/ReverseProxy/Configuration/ConfigurationConfigProvider.cs
  src/ReverseProxy/Configuration/DependencyInjection/ReverseProxyServiceCollectionExtensions.cs
  src/ReverseProxy/Middleware/HttpContextFeaturesExtensions.cs
  src/ReverseProxy/Middleware/LoadBalancingMiddleware.cs
  src/ReverseProxy/Middleware/PassiveHealthCheckMiddleware.cs
  src/ReverseProxy/Middleware/ProxyInvokerMiddleware.cs
  src/ReverseProxy/Middleware/SessionAffinityMiddleware.cs
  src/ReverseProxy/Service/LoadBalancing/RoundRobinLoadBalancingPolicy.cs
  src/ReverseProxy/Service/SessionAffinity/AffinitizeTransform.cs
  test/ReverseProxy.FunctionalTests/Common/TestEnvironment.cs
  test/ReverseProxy.ServiceFabric.Tests/ServiceDiscovery/Util/LabelsParserTests.cs
  test/ReverseProxy.Tests/Abstractions/RouteDiscovery/Contract/ProxyMatchTests.cs
  test/ReverseProxy.Tests/Abstractions/RouteDiscovery/Contract/ProxyRouteTests.cs
  test/ReverseProxy.Tests/Configuration/ConfigurationConfigProviderTests.cs
  test/ReverseProxy.Tests/IntegrationTests/RoutingTests.cs
  test/ReverseProxy.Tests/Middleware/PassiveHealthCheckMiddlewareTests.cs
  test/ReverseProxy.Tests/Middleware/ProxyInvokerMiddlewareTests.cs
  test/ReverseProxy.Tests/Middleware/ProxyPipelineInitializerMiddlewareTests.cs
  test/ReverseProxy.Tests/Service/Config/ConfigValidatorTests.cs
  test/ReverseProxy.Tests/Service/DynamicEndpoint/ProxyEndpointFactoryTests.cs
  test/ReverseProxy.Tests/Service/Management/ProxyConfigManagerTests.cs
  testassets/ReverseProxy.Code/Startup.cs
  testassets/ReverseProxy.Config/Startup.cs
Labels: Breaking-Change

#931 React to ProxyMatch, AddProxyConfigFilter renames in samples
  samples/ReverseProxy.Code.Sample/Startup.cs
  samples/ReverseProxy.ConfigFilter.Sample/Startup.cs
Labels: Auto-Merge

#932 React to ProxyMatch rename in docs
  docs/docfx/articles/configproviders.md
  docs/docfx/articles/header-routing.md
  docs/docfx/articles/service-fabric-int.md
Labels: Auto-Merge

#934 Use fixed package version for samples
  samples/BasicYarpSample/BasicYarpSample.csproj
  samples/Prometheus/ReverseProxy.Metrics-Promethius.Sample/ReverseProxy.Metrics.Promethius.Sample.csproj
  samples/ReverseProxy.Auth.Sample/ReverseProxy.Auth.Sample.csproj
  samples/ReverseProxy.Code.Sample/ReverseProxy.Code.Sample.csproj
  samples/ReverseProxy.Config.Sample/ReverseProxy.Config.Sample.csproj
  samples/ReverseProxy.ConfigFilter.Sample/ReverseProxy.ConfigFilter.Sample.csproj
  samples/ReverseProxy.Direct.Sample/ReverseProxy.Direct.Sample.csproj
  samples/ReverseProxy.Metrics.Sample/ReverseProxy.Metrics.Sample.csproj
  samples/ReverseProxy.ServiceFabric.Sample/ReverseProxy.ServiceFabric.Sample.csproj
  samples/ReverseProxy.Transforms.Sample/ReverseProxy.Transforms.Sample.csproj
Labels: Auto-Merge

#939 sealed internal class
  src/OperatorFramework/src/ResourceKinds.OpenApi/OpenApiResourceKindProvider.cs
  src/ReverseProxy.Kubernetes.Controller/Converters/ClusterTrasfer.cs
  src/ReverseProxy.Kubernetes.Controller/Converters/YarpIngressContext.cs
  src/ReverseProxy.Kubernetes.Controller/Converters/YarpIngressOptions.cs
  src/ReverseProxy.ServiceFabric/FabricWrapper/FabricClientWrapper.cs
  src/ReverseProxy.ServiceFabric/FabricWrapper/HealthClientWrapper.cs
  src/ReverseProxy.ServiceFabric/FabricWrapper/Model/ApplicationWrapper.cs
  src/ReverseProxy.ServiceFabric/FabricWrapper/Model/ReplicaWrapper.cs
  src/ReverseProxy.ServiceFabric/FabricWrapper/Model/ServiceWrapper.cs
  src/ReverseProxy.ServiceFabric/FabricWrapper/PropertyManagementClientWrapper.cs
  src/ReverseProxy.ServiceFabric/FabricWrapper/QueryClientWrapper.cs
  src/ReverseProxy.ServiceFabric/FabricWrapper/ServiceManagementClientWrapper.cs
  src/ReverseProxy.ServiceFabric/ServiceDiscovery/Discoverer.cs
  src/ReverseProxy.ServiceFabric/ServiceDiscovery/ServiceExtensionLabelsProvider.cs
  src/ReverseProxy.ServiceFabric/ServiceDiscovery/ServiceFabricConfigProvider.cs
  src/ReverseProxy/Configuration/CertificateConfigLoader.cs
  src/ReverseProxy/Configuration/ConfigurationConfigProvider.cs
  src/ReverseProxy/Configuration/ConfigurationSnapshot.cs
  src/ReverseProxy/Configuration/DependencyInjection/ReverseProxyBuilder.cs
  src/ReverseProxy/Middleware/LoadBalancingMiddleware.cs
  src/ReverseProxy/Middleware/ProxyInvokerMiddleware.cs
  src/ReverseProxy/Middleware/ProxyPipelineInitializerMiddleware.cs
  src/ReverseProxy/Middleware/SessionAffinityMiddleware.cs
  src/ReverseProxy/Service/Config/ActionTransformProvider.cs
  src/ReverseProxy/Service/Config/ConfigValidator.cs
  src/ReverseProxy/Service/Config/ForwardedTransformFactory.cs
  src/ReverseProxy/Service/Config/HttpMethodTransformFactory.cs
  src/ReverseProxy/Service/Config/PathTransformFactory.cs
  src/ReverseProxy/Service/Config/QueryTransformFactory.cs
  src/ReverseProxy/Service/Config/RequestHeadersTransformFactory.cs
  src/ReverseProxy/Service/Config/ResponseTransformFactory.cs
  src/ReverseProxy/Service/Config/TransformBuilder.cs
  src/ReverseProxy/Service/DynamicEndpoint/ProxyEndpointFactory.cs
  src/ReverseProxy/Service/HealthChecks/ConsecutiveFailuresHealthPolicy.cs
  src/ReverseProxy/Service/HealthChecks/DefaultProbingRequestFactory.cs
  src/ReverseProxy/Service/HealthChecks/DestinationHealthUpdater.cs
  src/ReverseProxy/Service/HealthChecks/TransportFailureRateHealthPolicy.cs
  src/ReverseProxy/Service/Management/EntityActionScheduler.cs
  src/ReverseProxy/Service/Management/ProxyConfigManager.cs
  src/ReverseProxy/Service/Proxy/HttpProxy.cs
  src/ReverseProxy/Service/Proxy/Infrastructure/CallbackProxyHttpClientFactory.cs
  src/ReverseProxy/Service/Proxy/ProxyErrorFeature.cs
  src/ReverseProxy/Service/Proxy/StreamCopyHttpContent.cs
  src/ReverseProxy/Service/Routing/HeaderMatcher.cs
  src/ReverseProxy/Service/Routing/HeaderMetadata.cs
  src/ReverseProxy/Service/RuntimeModel/Transforms/StructuredTransformer.cs
  src/ReverseProxy/Service/SessionAffinity/AffinitizeTransform.cs
  src/ReverseProxy/Service/SessionAffinity/AffinitizeTransformProvider.cs
  src/ReverseProxy/Service/SessionAffinity/CookieSessionAffinityProvider.cs
  src/ReverseProxy/Service/SessionAffinity/CustomHeaderSessionAffinityProvider.cs
  src/ReverseProxy/Service/SessionAffinity/RedistributeAffinityFailurePolicy.cs
  src/ReverseProxy/Service/SessionAffinity/Return503ErrorAffinityFailurePolicy.cs
  src/ReverseProxy/Utilities/AtomicCounter.cs
  src/ReverseProxy/Utilities/ParsedMetadataEntry.cs
  src/ReverseProxy/Utilities/RandomFactory.cs
  src/ReverseProxy/Utilities/ThreadStaticRandom.cs
  src/ReverseProxy/Utilities/TimerFactory.cs
  src/ReverseProxy/Utilities/TimerWrapper.cs
Labels: Auto-Merge

#951 Make ITransformBuilder available for IHttpProxy
  src/ReverseProxy/Configuration/DependencyInjection/BuilderExtensions/IReverseProxyBuilderExtensions.cs
  src/ReverseProxy/Configuration/DependencyInjection/ReverseProxyServiceCollectionExtensions.cs
Labels: Type: Bug
