Repository dotnet/yarp, pull requests merged in 2021-06, with the labels that each got.

#1063 Session Affinity API review feedback
  docs/docfx/articles/config-files.md
  docs/docfx/articles/session-affinity.md
  samples/ReverseProxy.Code.Sample/Startup.cs
  samples/ReverseProxy.Config.Sample/appsettings.json
  src/ReverseProxy.ServiceFabric/ServiceDiscovery/Util/LabelsParser.cs
  src/ReverseProxy/Configuration/ConfigProvider/ConfigurationConfigProvider.cs
  src/ReverseProxy/Configuration/ConfigValidator.cs
  src/ReverseProxy/Configuration/SessionAffinityConfig.cs
  src/ReverseProxy/SessionAffinity/AffinitizeTransform.cs
  src/ReverseProxy/SessionAffinity/AffinitizeTransformProvider.cs
  src/ReverseProxy/SessionAffinity/BaseSessionAffinityProvider.cs
  src/ReverseProxy/SessionAffinity/CookieSessionAffinityProvider.cs
  src/ReverseProxy/SessionAffinity/CustomHeaderSessionAffinityProvider.cs
  src/ReverseProxy/SessionAffinity/ISessionAffinityProvider.cs
  src/ReverseProxy/SessionAffinity/RedistributeAffinityFailurePolicy.cs
  src/ReverseProxy/SessionAffinity/Return503ErrorAffinityFailurePolicy.cs
  src/ReverseProxy/SessionAffinity/SessionAffinityConstants.cs
  src/ReverseProxy/SessionAffinity/SessionAffinityMiddleware.cs
  test/ReverseProxy.ServiceFabric.Tests/ServiceDiscovery/Util/LabelsParserTests.cs
  test/ReverseProxy.Tests/Configuration/ClusterConfigTests.cs
  test/ReverseProxy.Tests/Configuration/ConfigProvider/ConfigurationConfigProviderTests.cs
  test/ReverseProxy.Tests/Configuration/SessionAffinityConfigTests.cs
  test/ReverseProxy.Tests/SessionAffinity/AffinitizeTransformProviderTests.cs
  test/ReverseProxy.Tests/SessionAffinity/AffinitizeTransformTests.cs
  test/ReverseProxy.Tests/SessionAffinity/BaseSesstionAffinityProviderTests.cs
  test/ReverseProxy.Tests/SessionAffinity/CookieSessionAffinityProviderTests.cs
  test/ReverseProxy.Tests/SessionAffinity/CustomHeaderSessionAffinityProviderTests.cs
  test/ReverseProxy.Tests/SessionAffinity/RedistributeAffinityFailurePolicyTests.cs
  test/ReverseProxy.Tests/SessionAffinity/Return503ErrorAffinityFailurePolicyTests.cs
  test/ReverseProxy.Tests/SessionAffinity/SessionAffinityMiddlewareTests.cs
  testassets/ReverseProxy.Code/Startup.cs
  testassets/ReverseProxy.Config/appsettings.json
Labels: Auto-Merge, Breaking-Change

#1087 Misc API review
  docs/docfx/articles/config-files.md
  docs/docfx/articles/direct-forwarding.md
  docs/docfx/articles/middleware.md
  docs/docfx/articles/session-affinity.md
  samples/ReverseProxy.Code.Sample/Startup.cs
  samples/ReverseProxy.Config.Sample/appsettings.json
  src/ReverseProxy.ServiceFabric/ServiceDiscovery/Util/LabelsParser.cs
  src/ReverseProxy/Configuration/ConfigProvider/ConfigurationConfigProvider.cs
  src/ReverseProxy/Configuration/SessionAffinityConfig.cs
  src/ReverseProxy/Health/ActiveHealthCheckMonitor.cs
  src/ReverseProxy/Health/IActiveHealthCheckMonitor.cs
  src/ReverseProxy/Health/IPassiveHealthCheckPolicy.cs
  src/ReverseProxy/Health/PassiveHealthCheckMiddleware.cs
  src/ReverseProxy/Health/TransportFailureRateHealthPolicy.cs
  src/ReverseProxy/LoadBalancing/FirstLoadBalancingPolicy.cs
  src/ReverseProxy/LoadBalancing/ILoadBalancingPolicy.cs
  src/ReverseProxy/LoadBalancing/LeastRequestsLoadBalancingPolicy.cs
  src/ReverseProxy/LoadBalancing/LoadBalancingMiddleware.cs
  src/ReverseProxy/LoadBalancing/LoadBalancingPolicies.cs
  src/ReverseProxy/LoadBalancing/PowerOfTwoChoicesLoadBalancingPolicy.cs
  src/ReverseProxy/LoadBalancing/RandomLoadBalancingPolicy.cs
  src/ReverseProxy/LoadBalancing/RoundRobinLoadBalancingPolicy.cs
  src/ReverseProxy/Management/IReverseProxyBuilderExtensions.cs
  src/ReverseProxy/Management/ReverseProxyServiceCollectionExtensions.cs
  src/ReverseProxy/Model/HttpContextFeaturesExtensions.cs
  src/ReverseProxy/SessionAffinity/AffinitizeTransform.cs
  src/ReverseProxy/SessionAffinity/AffinitizeTransformProvider.cs
  src/ReverseProxy/SessionAffinity/BaseSessionAffinityPolicy.cs
  src/ReverseProxy/SessionAffinity/CookieSessionAffinityPolicy.cs
  src/ReverseProxy/SessionAffinity/CustomHeaderSessionAffinityPolicy.cs
  src/ReverseProxy/SessionAffinity/IAffinityFailurePolicy.cs
  src/ReverseProxy/SessionAffinity/ISessionAffinityPolicy.cs
  src/ReverseProxy/SessionAffinity/RedistributeAffinityFailurePolicy.cs
  src/ReverseProxy/SessionAffinity/Return503ErrorAffinityFailurePolicy.cs
  src/ReverseProxy/SessionAffinity/SessionAffinityConstants.cs
  src/ReverseProxy/SessionAffinity/SessionAffinityMiddleware.cs
  test/ReverseProxy.ServiceFabric.Tests/ServiceDiscovery/Util/LabelsParserTests.cs
  test/ReverseProxy.Tests/Configuration/ClusterConfigTests.cs
  test/ReverseProxy.Tests/Configuration/ConfigProvider/ConfigurationConfigProviderTests.cs
  test/ReverseProxy.Tests/Configuration/SessionAffinityConfigTests.cs
  test/ReverseProxy.Tests/Health/ActiveHealthCheckMonitorTests.cs
  test/ReverseProxy.Tests/Health/PassiveHealthCheckMiddlewareTests.cs
  test/ReverseProxy.Tests/Health/TransportFailureRateHealthPolicyTests.cs
  test/ReverseProxy.Tests/LoadBalancing/LoadBalancerMiddlewareTests.cs
  test/ReverseProxy.Tests/LoadBalancing/LoadBalancingPoliciesTests.cs
  test/ReverseProxy.Tests/SessionAffinity/AffinitizeTransformProviderTests.cs
  test/ReverseProxy.Tests/SessionAffinity/AffinitizeTransformTests.cs
  test/ReverseProxy.Tests/SessionAffinity/BaseSesstionAffinityPolicyTests.cs
  test/ReverseProxy.Tests/SessionAffinity/CookieSessionAffinityPolicyTests.cs
  test/ReverseProxy.Tests/SessionAffinity/CustomHeaderSessionAffinityPolicyTests.cs
  test/ReverseProxy.Tests/SessionAffinity/RedistributeAffinityFailurePolicyTests.cs
  test/ReverseProxy.Tests/SessionAffinity/Return503ErrorAffinityFailurePolicyTests.cs
  test/ReverseProxy.Tests/SessionAffinity/SessionAffinityMiddlewareTests.cs
  testassets/ReverseProxy.Code/Controllers/HealthController.cs
  testassets/ReverseProxy.Code/Startup.cs
  testassets/ReverseProxy.Config/appsettings.json
  testassets/ReverseProxy.Direct/Startup.cs
Labels: Breaking-Change

#1099 Default X-Forwarded-* transform action is to set the header value
  docs/docfx/articles/transforms.md
  src/ReverseProxy/Forwarder/RequestUtilities.cs
  src/ReverseProxy/Transforms/ForwardedTransformActions.cs
  src/ReverseProxy/Transforms/ForwardedTransformExtensions.cs
  src/ReverseProxy/Transforms/ForwardedTransformFactory.cs
  src/ReverseProxy/Transforms/RequestHeaderForwardedTransform.cs
  src/ReverseProxy/Transforms/RequestHeaderXForwardedForTransform.cs
  src/ReverseProxy/Transforms/RequestHeaderXForwardedHostTransform.cs
  src/ReverseProxy/Transforms/RequestHeaderXForwardedPrefixTransform.cs
  src/ReverseProxy/Transforms/RequestHeaderXForwardedProtoTransform.cs
  src/ReverseProxy/Transforms/RequestTransform.cs
  test/ReverseProxy.Tests/Transforms/Builder/TransformBuilderTests.cs
  test/ReverseProxy.Tests/Transforms/ForwardedTransformExtensionsTests.cs
  test/ReverseProxy.Tests/Transforms/RequestHeaderForwardedTransformTests.cs
  test/ReverseProxy.Tests/Transforms/RequestHeaderXForwardedForTransformTests.cs
  test/ReverseProxy.Tests/Transforms/RequestHeaderXForwardedHostTransformTests.cs
  test/ReverseProxy.Tests/Transforms/RequestHeaderXForwardedPrefixTransformTests.cs
  test/ReverseProxy.Tests/Transforms/RequestHeaderXForwardedProtoTransformTests.cs
  testassets/ReverseProxy.Config/appsettings.json
Labels: Breaking-Change

#1133 Fix "Getting Started" link
  README.md
Labels: Auto-Merge
