Repository dotnet/yarp, pull requests merged in 2025-05, with the labels that each got.

#2845 Enable binskim
  azure-pipelines.yml
Labels: Type: Infrastructure

#2860 docs: fix a typo
  docs/designs/config.md
Labels: Type: Documentation

#2856 Introduce service port driven backend protocol to support different protocols routing in same ingress.
  src/Kubernetes.Controller/Converters/YarpParser.cs
  test/Kubernetes.Tests/IngressConversionTests.cs
  test/Kubernetes.Tests/testassets/external-name-ingress/clusters.json
  test/Kubernetes.Tests/testassets/https-service-port-protocol/clusters.json
  test/Kubernetes.Tests/testassets/https-service-port-protocol/ingress.yaml
  test/Kubernetes.Tests/testassets/https-service-port-protocol/routes.json
Labels: Kubernetes Ingress Controller
